### ISSUE TITLE
Read multiple files 

### ISSUE THREAD

**Issue by cdmuir** [muir-lab/licorer#13]
If multiple file names are given in the file argument, then the data should be combined. You can probably use `purrr::map_dfr()` to accomplish this. But then what happens to attributes? We'll have to think carefully about this and discuss.

**Comment by DanielTrupp** [comment]
created a prototype `combine_licor` function

**Comment by DanielTrupp** [comment]
If multiple filenames are given, licor will read them in and combine them into one "multi-licor" The attributes present are either a combination of all licor data structures, as in the names and subsetting options, or are preserved in a list in the header data, with their position in the list corresponding to their file index.
