### ISSUE TITLE
Lazy loading failed

### ISSUE THREAD

**Issue by jbwst** [muir-lab/licorer#18]
Hi all, thanks for sharing this early version! Just a quick note to let you know I tried installing and it failed. Here's what I got:

> remotes::install_github("muir-lab/licorer")
Downloading GitHub repo muir-lab/licorer@HEAD
✓  checking for file ‘/private/var/folders/xt/gktx9xt115b7kjh1bybbw7840000gp/T/RtmpTVkn36/remotes5a212e737203/muir-lab-licorer-69f8678/DESCRIPTION’ ...
─  preparing ‘licorer’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘licorer_0.0.1.tar.gz’
   
* installing *source* package ‘licorer’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘units’ was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package ‘licorer’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/licorer’
Error: Failed to install 'licorer' from GitHub:
  (converted from warning) installation of package ‘/var/folders/xt/gktx9xt115b7kjh1bybbw7840000gp/T//RtmpTVkn36/file5a211d423ac8/licorer_0.0.1.tar.gz’ had non-zero exit status

**Comment by jbwst** [comment]
Er, should read the error before posting here...updating R from my current 4.0.1 to 4.0.2 now...

**Comment by cdmuir** [comment]
Thanks for testing it out. I wonder if you have to have **units** package installed first?

**Comment by jbwst** [comment]
R version 4.0.2 installed, licorer successfully installed.  :-)

**Comment by cdmuir** [comment]
Thanks. We will need to check on this. I don't think it should be necessary that everyone update to the bleeding edge version for this work.
